In [1]:
import pandas as pd
pd.options.display.max_rows = 200
pd.options.display.max_columns = 200

In [2]:
res = pd.read_csv('../results/age_add_edge.csv')

In [3]:
t_res=res[['dataset','nodes_rate','add_edge_rate','ARI','NMI','ACC','Micro F1','Macro F1','Elapsed Time']]

In [4]:
tmp=t_res.groupby(['dataset','nodes_rate','add_edge_rate'],as_index=False).mean().round(4)

In [5]:
df_res = pd.DataFrame()

In [6]:
df_res = pd.concat([df_res,tmp[tmp['dataset']=='Cora']],axis=0)
tmp[tmp['dataset']=='Cora']

,dataset,nodes_rate,add_edge_rate,ARI,NMI,ACC,Micro F1,Macro F1,Elapsed Time
45,Cora,0.25,0.1,0.5171,0.5887,0.7446,0.7446,0.7043,39.5487
46,Cora,0.25,0.3,0.5567,0.6157,0.7644,0.7644,0.7213,44.2765
47,Cora,0.25,0.5,0.5848,0.6375,0.7793,0.7793,0.7338,37.3782
48,Cora,0.25,0.7,0.5985,0.6487,0.7848,0.7848,0.7366,47.0592
49,Cora,0.25,0.9,0.5990,0.6570,0.7889,0.7889,0.7437,43.4361
50,Cora,0.50,0.1,0.5439,0.6083,0.7591,0.7591,0.7167,45.3105
51,Cora,0.50,0.3,0.6073,0.6593,0.7937,0.7937,0.7481,41.2076
52,Cora,0.50,0.5,0.6426,0.6857,0.8080,0.8080,0.7510,46.0462
53,Cora,0.50,0.7,0.6892,0.7135,0.8353,0.8353,0.7994,39.4139
54,Cora,0.50,0.9,0.7153,0.7247,0.8577,0.8577,0.8387,45.1103
55,Cora,0.75,0.1,0.5781,0.6273,0.7719,0.7719,0.7261,39.1692
56,Cora,0.75,0.3,0.6643,0.6917,0.8178,0.8178,0.7663,49.1936
57,Cora,0.75,0.5,0.7654,0.7506,0.8812,0.8812,0.8590,39.1693
58,Cora,0.75,0.7,0.8038,0.7792,0.9090,0.9090,0.9052,49.6006
59,Cora,0.75,0.9,0.8004,0.7794,0.8959,0.8959,0.8615,41.4546

In [7]:
df_res = pd.concat([df_res,tmp[tmp['dataset']=='Citeseer']],axis=0)
tmp[tmp['dataset']=='Citeseer']#.sort_values(by=['ACC'],ascending=False)

,dataset,nodes_rate,add_edge_rate,ARI,NMI,ACC,Micro F1,Macro F1,Elapsed Time
30,Citeseer,0.25,0.1,0.4553,0.4496,0.7001,0.7001,0.6467,54.8372
31,Citeseer,0.25,0.3,0.4750,0.4650,0.7128,0.7128,0.6570,52.4926
32,Citeseer,0.25,0.5,0.4807,0.4718,0.7169,0.7169,0.6621,49.6352
33,Citeseer,0.25,0.7,0.4771,0.4702,0.7141,0.7141,0.6605,51.5014
34,Citeseer,0.25,0.9,0.4903,0.4839,0.7225,0.7225,0.6683,48.7835
35,Citeseer,0.50,0.1,0.4818,0.4678,0.7153,0.7153,0.6601,49.3314
36,Citeseer,0.50,0.3,0.4938,0.4830,0.7203,0.7203,0.6652,53.3492
37,Citeseer,0.50,0.5,0.5166,0.5006,0.7340,0.7340,0.6786,48.6145
38,Citeseer,0.50,0.7,0.5290,0.5101,0.7410,0.7410,0.6839,49.0569
39,Citeseer,0.50,0.9,0.5468,0.5232,0.7533,0.7533,0.6947,46.3708
40,Citeseer,0.75,0.1,0.4818,0.4722,0.7172,0.7172,0.6627,51.3216
41,Citeseer,0.75,0.3,0.5326,0.5195,0.7464,0.7464,0.6876,47.8954
42,Citeseer,0.75,0.5,0.5580,0.5368,0.7605,0.7605,0.6982,52.9336
43,Citeseer,0.75,0.7,0.5752,0.5521,0.7689,0.7689,0.7108,40.3491
44,Citeseer,0.75,0.9,0.5949,0.5694,0.7813,0.7813,0.7224,44.1258

In [8]:
df_res = pd.concat([df_res,tmp[tmp['dataset']=='Pubmed']],axis=0)
tmp[tmp['dataset']=='Pubmed']#.sort_values(by=['ACC'],ascending=False)

,dataset,nodes_rate,add_edge_rate,ARI,NMI,ACC,Micro F1,Macro F1,Elapsed Time
90,Pubmed,0.25,0.1,0.3309,0.3122,0.7100,0.7100,0.7014,413.9502
91,Pubmed,0.25,0.3,0.3337,0.3192,0.7119,0.7119,0.7027,337.7265
92,Pubmed,0.25,0.5,0.3376,0.3242,0.7143,0.7143,0.7056,341.2535
93,Pubmed,0.25,0.7,0.3440,0.3304,0.7180,0.7180,0.7089,287.1856
94,Pubmed,0.25,0.9,0.3434,0.3332,0.7181,0.7181,0.7091,409.6852
95,Pubmed,0.50,0.1,0.3392,0.3259,0.7160,0.7160,0.7063,329.8630
96,Pubmed,0.50,0.3,0.3578,0.3460,0.7287,0.7287,0.7193,299.3121
97,Pubmed,0.50,0.5,0.3809,0.3669,0.7441,0.7441,0.7348,413.6961
98,Pubmed,0.50,0.7,0.4049,0.3828,0.7571,0.7571,0.7477,313.0373
99,Pubmed,0.50,0.9,0.4189,0.3952,0.7655,0.7655,0.7560,340.5323
100,Pubmed,0.75,0.1,0.3470,0.3403,0.7216,0.7216,0.7119,291.3131
101,Pubmed,0.75,0.3,0.4154,0.3949,0.7635,0.7635,0.7541,326.4972
102,Pubmed,0.75,0.5,0.4880,0.4434,0.8002,0.8002,0.7898,380.1792
103,Pubmed,0.75,0.7,0.5268,0.4694,0.8177,0.8177,0.8063,385.6964
104,Pubmed,0.75,0.9,0.5491,0.4837,0.8275,0.8275,0.8160,416.4655

In [9]:
df_res = pd.concat([df_res,tmp[tmp['dataset']=='ACM']],axis=0)
tmp[tmp['dataset']=='ACM']#.sort_values(by=['ACC'],ascending=False)

,dataset,nodes_rate,add_edge_rate,ARI,NMI,ACC,Micro F1,Macro F1,Elapsed Time
0,ACM,0.25,0.1,0.7817,0.7261,0.9214,0.9214,0.9212,33.1215
1,ACM,0.25,0.3,0.7839,0.7284,0.9223,0.9223,0.9221,41.5348
2,ACM,0.25,0.5,0.7847,0.7288,0.9226,0.9226,0.9224,33.4222
3,ACM,0.25,0.7,0.7859,0.7309,0.9231,0.9231,0.9228,37.6966
4,ACM,0.25,0.9,0.7875,0.7337,0.9236,0.9236,0.9234,33.9557
5,ACM,0.50,0.1,0.7864,0.7319,0.9232,0.9232,0.9230,35.0077
6,ACM,0.50,0.3,0.7961,0.7429,0.9271,0.9271,0.9270,35.7557
7,ACM,0.50,0.5,0.8026,0.7497,0.9296,0.9296,0.9296,33.1385
8,ACM,0.50,0.7,0.8049,0.7519,0.9305,0.9305,0.9305,36.6959
9,ACM,0.50,0.9,0.8106,0.7589,0.9327,0.9327,0.9327,33.9456
10,ACM,0.75,0.1,0.7963,0.7436,0.9271,0.9271,0.9270,35.3932
11,ACM,0.75,0.3,0.8054,0.7519,0.9307,0.9307,0.9307,31.6122
12,ACM,0.75,0.5,0.8196,0.7655,0.9361,0.9361,0.9360,33.3751
13,ACM,0.75,0.7,0.8254,0.7722,0.9383,0.9383,0.9383,27.9643
14,ACM,0.75,0.9,0.8386,0.7852,0.9433,0.9433,0.9433,41.1456

In [10]:
df_res = pd.concat([df_res,tmp[tmp['dataset']=='BlogCatalog']],axis=0)
tmp[tmp['dataset']=='BlogCatalog']#.sort_values(by=['ACC'],ascending=False)

,dataset,nodes_rate,add_edge_rate,ARI,NMI,ACC,Micro F1,Macro F1,Elapsed Time
15,BlogCatalog,0.25,0.1,0.2598,0.3443,0.5588,0.5588,0.5206,117.1909
16,BlogCatalog,0.25,0.3,0.2845,0.3663,0.5788,0.5788,0.5417,109.7761
17,BlogCatalog,0.25,0.5,0.2985,0.3757,0.5862,0.5862,0.5467,103.0447
18,BlogCatalog,0.25,0.7,0.3127,0.3887,0.5964,0.5964,0.5567,128.7600
19,BlogCatalog,0.25,0.9,0.3293,0.4021,0.6093,0.6093,0.5700,129.8320
20,BlogCatalog,0.50,0.1,0.2697,0.3533,0.5647,0.5647,0.5253,126.5440
21,BlogCatalog,0.50,0.3,0.3330,0.4050,0.6118,0.6118,0.5722,122.4997
22,BlogCatalog,0.50,0.5,0.4107,0.4615,0.6682,0.6682,0.6282,109.6865
23,BlogCatalog,0.50,0.7,0.4894,0.5187,0.7172,0.7172,0.6753,108.4732
24,BlogCatalog,0.50,0.9,0.5277,0.5494,0.7381,0.7381,0.6952,123.1167
25,BlogCatalog,0.75,0.1,0.3185,0.3946,0.6024,0.6024,0.5642,111.9246
26,BlogCatalog,0.75,0.3,0.5022,0.5321,0.7247,0.7247,0.6822,123.7113
27,BlogCatalog,0.75,0.5,0.5947,0.6145,0.7730,0.7730,0.7283,117.8845
28,BlogCatalog,0.75,0.7,0.6408,0.6606,0.7973,0.7973,0.7548,113.3494
29,BlogCatalog,0.75,0.9,0.6634,0.6848,0.8102,0.8102,0.7710,116.3237

In [11]:
df_res = pd.concat([df_res,tmp[tmp['dataset']=='Flickr']],axis=0)
tmp[tmp['dataset']=='Flickr']#.sort_values(by=['ACC'],ascending=False)

,dataset,nodes_rate,add_edge_rate,ARI,NMI,ACC,Micro F1,Macro F1,Elapsed Time
75,Flickr,0.25,0.1,0.1726,0.2952,0.4014,0.4014,0.3746,244.7457
76,Flickr,0.25,0.3,0.1857,0.3185,0.4144,0.4144,0.3962,245.2180
77,Flickr,0.25,0.5,0.1987,0.3378,0.4289,0.4289,0.4336,227.9382
78,Flickr,0.25,0.7,0.2148,0.3604,0.4522,0.4522,0.4598,248.7706
79,Flickr,0.25,0.9,0.2300,0.3748,0.4807,0.4807,0.4664,255.4958
80,Flickr,0.50,0.1,0.1871,0.3182,0.4136,0.4136,0.3908,250.4485
81,Flickr,0.50,0.3,0.2423,0.3936,0.4848,0.4848,0.4899,277.5454
82,Flickr,0.50,0.5,0.3068,0.4557,0.5476,0.5476,0.5524,264.2488
83,Flickr,0.50,0.7,0.3536,0.4972,0.6254,0.6254,0.6267,173.0623
84,Flickr,0.50,0.9,0.3895,0.5200,0.6635,0.6635,0.6617,235.8321
85,Flickr,0.75,0.1,0.2108,0.3423,0.4495,0.4495,0.4294,242.4966
86,Flickr,0.75,0.3,0.3676,0.4973,0.6238,0.6238,0.6214,224.2364
87,Flickr,0.75,0.5,0.5316,0.6014,0.7671,0.7671,0.7689,241.4600
88,Flickr,0.75,0.7,0.6147,0.6537,0.8128,0.8128,0.8125,243.4002
89,Flickr,0.75,0.9,0.6636,0.6859,0.8378,0.8378,0.8371,221.4021

In [12]:
df_res = pd.concat([df_res,tmp[tmp['dataset']=='CoraFull']],axis=0)
tmp[tmp['dataset']=='CoraFull']#.sort_values(by=['ACC'],ascending=False)

,dataset,nodes_rate,add_edge_rate,ARI,NMI,ACC,Micro F1,Macro F1,Elapsed Time
60,CoraFull,0.25,0.1,0.1908,0.5070,0.3925,0.3925,0.2836,1161.8072
61,CoraFull,0.25,0.3,0.2045,0.5056,0.3917,0.3917,0.2764,1088.7723
62,CoraFull,0.25,0.5,0.1885,0.5018,0.3878,0.3878,0.2720,1093.1102
63,CoraFull,0.25,0.7,0.2036,0.5112,0.4026,0.4026,0.2802,895.5293
64,CoraFull,0.25,0.9,0.1700,0.4965,0.3834,0.3834,0.2732,1108.7710
65,CoraFull,0.50,0.1,0.2092,0.5089,0.3857,0.3857,0.2653,1059.9908
66,CoraFull,0.50,0.3,0.2062,0.5105,0.4024,0.4024,0.2838,1044.3423
67,CoraFull,0.50,0.5,0.1938,0.5048,0.3862,0.3862,0.2747,1116.3666
68,CoraFull,0.50,0.7,0.1717,0.4956,0.3802,0.3802,0.2691,1322.7285
69,CoraFull,0.50,0.9,0.2098,0.5118,0.4027,0.4027,0.2803,1218.2142
70,CoraFull,0.75,0.1,0.2114,0.5130,0.4108,0.4108,0.2877,1259.0253
71,CoraFull,0.75,0.3,0.2183,0.5182,0.4128,0.4128,0.2958,975.1649
72,CoraFull,0.75,0.5,0.1740,0.4960,0.3816,0.3816,0.2718,1323.2040
73,CoraFull,0.75,0.7,0.1598,0.4917,0.3794,0.3794,0.2725,1294.1508
74,CoraFull,0.75,0.9,0.2078,0.5128,0.3974,0.3974,0.2780,1017.4428

In [13]:
df_res.to_csv('../results/age_add_edge_sort.csv')