In [1]:
import pandas as pd
import copy

In [2]:
res = pd.read_csv('../results/AGCN_0.csv')

In [3]:
res

,dataset,gpu,dir,seed,nodes_rate,add_edge_rate,target_path,model,hidden1,hidden2,...,pretrain_ae_epochs,epochs,v,pretrain_ae_lr,ARI,NMI,ACC,Micro F1,Macro F1,Elapsed Time
0,CoraFull,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.017432,0.209927,0.120194,0.120194,0.054380,399.347087
1,CoraFull,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.032609,0.243215,0.139797,0.139797,0.052547,390.120266
2,CoraFull,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.032028,0.182474,0.104734,0.104734,0.023800,310.254148
3,CoraFull,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.031664,0.239764,0.141262,0.141262,0.064887,299.315499
4,CoraFull,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.036465,0.231868,0.111150,0.111150,0.029317,334.717007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,ACM,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.385855,0.406881,0.642645,0.642645,0.514325,36.082956
66,ACM,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.400259,0.428766,0.650579,0.650579,0.519963,35.997230
67,ACM,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.351713,0.351642,0.589091,0.589091,0.479493,36.175457
68,ACM,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.396449,0.418470,0.648264,0.648264,0.518768,42.436485
69,ACM,2,./data,False,0.5,0.5,results/AGCN_0.csv,AGCN,500,500,...,30,200,1,0.001,0.608658,0.564286,0.845950,0.845950,0.842120,32.605359

In [5]:
res['model'].value_counts()

AGCN    70
Name: model, dtype: int64

In [6]:
need_cols = ['dataset','model','ARI','NMI','ACC','Micro F1','Macro F1','Elapsed Time']
t_res=res[need_cols]

In [7]:
t_res = t_res[t_res['model']=='AGCN']

In [8]:

t_mean = t_res.groupby(['dataset'],as_index=False).mean().round(4).T
t_mean

,0,1,2,3,4,5,6
dataset,ACM,BlogCatalog,Citeseer,Cora,CoraFull,Flickr,Pubmed
ARI,0.4588,0.092,0.2564,0.2426,0.0322,0.0068,0.2378
NMI,0.457,0.175,0.2892,0.3269,0.2195,0.0258,0.266
ACC,0.7087,0.3243,0.5158,0.5133,0.1212,0.1339,0.6381
Micro F1,0.7087,0.3243,0.5158,0.5133,0.1212,0.1339,0.6381
Macro F1,0.63,0.1977,0.4205,0.4141,0.0408,0.0422,0.6443
Elapsed Time,37.1007,98.4619,48.4159,43.9455,318.365,141.024,140.607

In [9]:
t_std = t_res.groupby(['dataset'],as_index=False).std().round(4).T
t_std

                   0            1         2       3         4       5       6
dataset          ACM  BlogCatalog  Citeseer    Cora  CoraFull  Flickr  Pubmed
ARI           0.1158       0.0418    0.0881  0.0473    0.0087  0.0134  0.0247
NMI           0.0912       0.0453    0.0704  0.0485    0.0264  0.0375  0.0167
ACC           0.1081       0.0491    0.0928  0.0423     0.015  0.0239  0.0213
Micro F1      0.1081       0.0491    0.0928  0.0423     0.015  0.0239  0.0213
Macro F1      0.1648       0.0518    0.1302  0.0564    0.0155  0.0184  0.0233
Elapsed Time  2.6436      16.5399   13.7402  10.428   48.5104  8.5019  18.817

In [10]:
t_mean_std = copy.deepcopy(t_mean)

In [11]:
for col in t_mean_std.columns.values:
    t_mean_std.iloc[1:-1,col]=t_mean_std.iloc[1:-1,col].astype(str) + '±' + t_std.iloc[1:-1,col].astype(str)

In [12]:
t_mean_std

,0,1,2,3,4,5,6
dataset,ACM,BlogCatalog,Citeseer,Cora,CoraFull,Flickr,Pubmed
ARI,0.4588±0.1158,0.092±0.0418,0.2564±0.0881,0.2426±0.0473,0.0322±0.0087,0.0068±0.0134,0.2378±0.0247
NMI,0.457±0.0912,0.175±0.0453,0.2892±0.0704,0.3269±0.0485,0.2195±0.0264,0.0258±0.0375,0.266±0.0167
ACC,0.7087±0.1081,0.3243±0.0491,0.5158±0.0928,0.5133±0.0423,0.1212±0.015,0.1339±0.0239,0.6381±0.0213
Micro F1,0.7087±0.1081,0.3243±0.0491,0.5158±0.0928,0.5133±0.0423,0.1212±0.015,0.1339±0.0239,0.6381±0.0213
Macro F1,0.63±0.1648,0.1977±0.0518,0.4205±0.1302,0.4141±0.0564,0.0408±0.0155,0.0422±0.0184,0.6443±0.0233
Elapsed Time,37.1007,98.4619,48.4159,43.9455,318.365,141.024,140.607